apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Production project
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  #- group: 'rbac.authorization.k8s.io'
  #  kind: '*'
  #- group: 'apiextensions.k8s.io'
  #  kind: 'CustomResourceDefinition'
  - group: 'argoproj.io'
    kind: AppProject
  #- group: '*'
  #  kind: '*'
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: StatefulSet
  - group: '' 
    kind: Service
  - group: 'argoproj.io'
    kind: Application
  - group: 'extensions/v1beta1'
    kind: Ingress
  - group: 'extensions'
    kind: Ingress
  - group: 'networking.k8s.io'
    kind: Ingress
